spring.config.activate.on-profile: local-datasource

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meet?autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverZoneId=UTC
    username: meet-in
    password: meet
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1140000
      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: false
        format_sql: false
        order_by.default_null_ordering: first
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

---
spring.config.activate.on-profile: dev-datasource
