spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meet-in?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: gongsung403
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
      auto-commit: false
      maximum-pool-size: 100
      max-lifetime: 1140000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create
    #      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: beans, conditions