spring:
  profiles:
    active: local
    group:
      local: local-repository, local-service-meta
      dev: dev-repository, dev-service-meta
  config:
    import:
      - config/service-meta.yml
      - application-repository.yml
server:
  port: 8081
